repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: pytest tests/ --cov=src --cov-fail-under=80
    language: system
    pass_filenames: false
    always_run: true
